@startuml
[*] --> Proyectada

state "Proyectada" as Proyectada : Silueta estable sobre Superficie
state "EnTransición" as Dinamica : Recalculando Silueta en tiempo real

Proyectada --> Dinamica : cambia de posición
Dinamica --> Proyectada : se estabiliza

' Finalización del ciclo por eliminación de causas
Proyectada --> [*] : apagar fuente o retirar cuerpo
Dinamica --> [*] : apagar fuente o retirar cuerpo

@enduml